{
 "title": "GPS Receiver",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(gpsd_fix_mode, instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(gpsd_fix_mode, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPSD Fix/Mode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gpsd_fix_mode{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "SV Total / Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gpsd_space_vehicles_total{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_space_vehicles_used{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "SV Azimuth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "gpsd_space_vehicle_azimuth{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{prn}}"
    }
   ]
  },
  {
   "title": "SV Elevation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "gpsd_space_vehicle_elevation{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{prn}}"
    }
   ]
  },
  {
   "title": "SV SNR",
   "type": "timeseries",
   "description": "Signa/Noise Ration per Space Vehicle",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "gpsd_space_vehicle_signal_noise_ratio{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{prn}}"
    }
   ]
  },
  {
   "title": "Dilution of Precision",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpsd_dilution_of_precision_time{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_dilution_of_precision_altitude{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_dilution_of_precision_position{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Estimated Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "gpsd_estimated_error_timestamp{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_altitude{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_climb{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_direction{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_latitude{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_longitude{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gpsd_estimated_error_speed{job=\"gpsd\", instance=\"$instance\", device=\"$device\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}